export class signInPageLocators {
  static emailInput = "//input[@id='email_create']"
  static createAnAccount = "//button[@id='SubmitCreate']"
  static createAccountError = "//div[@id='create_account_error']"
  static heading = "//h1[@class='page-heading']"
  static Mr = '//div[@class="radio-inline"][1]'
  static firstName = "//input[@id='customer_firstname']"
  static lastName = "//input[@id='customer_lastname']"
  static password = "//input[@id='passwd']"
  static date = "//select[@id='days']"
  static month = "//select[@id='months']"
  static year = "//select[@id='years']"
  static address = "//input[@id='address1']"
  static city = "//input[@id='city']"
  static state = "//select[@id='id_state']"
  static zipcode = "//input[@id='postcode']"
  static country = "//select[@id='id_country']"
  static mobile= "//input[@id='phone_mobile']"
  static registerButton = "//button[@id='submitAccount']"
  static emailSignIn = "//input[@id='email']"
  static passwordSignin = "//input[@id='passwd']"
  static signInButton = "//button[@id='SubmitLogin']"
  static authenticationFail = "//h1[@class='page-heading']/following-sibling::div[1]"
}
